version: '3.9'

services:
  bot_creator:
    build:
      context: .
      dockerfile: Dockerfile.app
    ports:
      - "5000:5000"
    volumes:
      - ./backend:/app
      - ./backend/data:/app/data                # ✅ ADD THIS
      - ./backend/generated_bots:/app/generated_bots
      - ./backend/uploaded_files:/app/uploaded_files
      - ./backend/index_storage:/app/index_storage
    depends_on:
      - ollama

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.frontend
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules

  ollama:
    image: ollama/ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama

volumes:
  ollama_data:
